dependencies:
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- alias: activiti-cloud
  name: activiti-cloud-full-example
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.4.0
