expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 35.228.74.24.nip.io
    exposer: Ingress
    http: "true"
    tlsacme: "false"
    pathMode: ""
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system

global:
  keycloak:
    url: "http://activiti-keycloak.35.228.74.24.nip.io/auth"
  gateway:
    host: &gatewayhost "activiti-cloud-gateway.35.228.74.24.nip.io" 
 
runtime-bundle:
  enabled: true
activiti-cloud-connector:
  enabled: true  
activiti-cloud-modeling:
  enabled: true

application:
  runtime-bundle:
    enabled: true
  activiti-cloud-connector:
    enabled: true

activiti-cloud:
  activiti-cloud-modeling:
    enabled: true

  application:
    runtime-bundle:
      enabled: true
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 1024Mi
    activiti-cloud-connector:
      enabled: true  
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 1024Mi
    activiti-cloud-query:
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 1024Mi
    activiti-cloud-audit:
      resources:
        limits:
          cpu: 1500m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 1024Mi

  infrastructure:
    activiti-keycloak:
      keycloak:
        enabled: true
        keycloak:
          ingress:
            enabled: true
            path: /
            proxyBufferSize: "16k"
            hosts:
              - "activiti-keycloak.35.228.74.24.nip.io"
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /
              nginx.ingress.kubernetes.io/configuration-snippet: |
                more_set_headers 'Access-Control-Allow-Methods: "POST, GET, OPTIONS, PUT, PATCH, DELETE"';
                more_set_headers 'Access-Control-Allow-Credentials: true';
                more_set_headers 'Access-Control-Allow-Headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,authorization"';
                more_set_headers 'Access-Control-Allow-Origin: $http_origin';
              nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
          preStartScript: |
            /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
            /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
            cp /realm/activiti-realm.json .
            sed -i 's/placeholder.com/*/g' activiti-realm.json
    
    activiti-cloud-gateway:
      ingress:
        enabled: true
        hostName: "activiti-cloud-gateway.35.228.74.24.nip.io"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/enable-cors: true
          nginx.ingress.kubernetes.io/cors-allow-headers: "*"
          nginx.ingress.kubernetes.io/x-forwarded-prefix: true
